# Generated by Django 5.1.6 on 2025-03-09 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='statut',
        ),
    ]
