# Generated by Django 5.1.6 on 2025-03-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Étudiant'), ('professeur', 'Professeur')], max_length=10),
        ),
    ]
