# Generated by Django 5.1.6 on 2025-03-14 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatistiquesPeriodiques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_type', models.CharField(choices=[('trimestriel', 'Trimestriel'), ('annuel', 'Annuel')], max_length=20)),
                ('debut_periode', models.DateField()),
                ('fin_periode', models.DateField()),
                ('nombre_taches_total', models.IntegerField(default=0)),
                ('nombre_taches_completees', models.IntegerField(default=0)),
                ('nombre_taches_dans_delai', models.IntegerField(default=0)),
                ('pourcentage_completion', models.FloatField(default=0)),
                ('pourcentage_dans_delai', models.FloatField(default=0)),
                ('prime_eligible', models.BooleanField(default=False)),
                ('montant_prime', models.IntegerField(default=0)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'periode_type', 'debut_periode')},
            },
        ),
    ]
