# Generated by Django 5.1.6 on 2025-03-10 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_projet_statut'),
        ('tache', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='progression',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tache',
            name='projet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='project.projet'),
            preserve_default=False,
        ),
    ]
