# Generated by Django 5.1.6 on 2025-03-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache', '0002_tache_progression_tache_projet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='date_echeance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='date_fin_reelle',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='termine_dans_delai',
            field=models.BooleanField(default=False),
        ),
    ]
