# Generated by Django 5.1.6 on 2025-03-15 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_projet_statut'),
        ('tache', '0003_tache_date_echeance_tache_date_fin_reelle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='project.projet'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='statut',
            field=models.CharField(choices=[('À faire', 'À faire'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='à faire', max_length=50),
        ),
    ]
